### ISSUE TITLE
Training process

### ISSUE THREAD

**Issue by liu6381810** [kohillyang/mx-openpose#1]
Hi,
Thanks for your great work!
I have some questions about training
1.What the sigma do you choose to generate the ground truth heat map
2.What's your loss in the first iteration and you say you have loss 80-110 after 10000 iterations
Is the loss the sum of 6 stages?
3.Do we need to generate background heat map for training

Thanks!

**Comment by kohillyang** [comment]
1. 7.0, as the code says, since you can replace it by just a circle(I tested it  and the accuracy is 0.01 lower than using Gaussian dot. 
2. The first loss is about 600-900. It's the sum of first and the last stage.
3. Sorry, I don't know what background heat map is, maybe there is no need to do that.
